import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AutoBlogSite.com - High-Quality AI Powered Blog by AI Writer",
  description: "Experience the future of content with AutoBlogSite.com. A professional AI-powered blog where every post is generated 100% by AI Writer. Discover automated insights on technology, trends, and innovation.",
  openGraph: {
    title: "AutoBlogSite.com - AI Powered Blog by AI Writer",
    description: "Every article you read here is generated by Artificial Intelligence (AI Writer) without human intervention. A demonstration of modern automation.",
    url: "https://autoblogsite.com",
    siteName: "AutoBlogSite.com",
    images: [
      {
        url: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=1200&q=80",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AutoBlogSite.com - AI Powered Blog by AI Writer",
    description: "Every article you read here is generated by Artificial Intelligence (AI Writer) without human intervention.",
    images: ["https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=1200&q=80"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Lora:ital,wght@0,400..700;1,400..700&family=Charter&display=swap" rel="stylesheet" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
