import Link from 'next/link';
import Header from '@/components/Header';
import ArticleFeed from '@/components/ArticleFeed';
import { getArticles } from '@/lib/articles';

export default function Home() {
  const allArticles = getArticles();
  const initialArticles = allArticles.slice(0, 10);
  const hasMore = allArticles.length > 10;

  return (
    <div>
      <Header />

      <main className="main-grid">
        <ArticleFeed initialArticles={initialArticles} initialHasMore={hasMore} />

        <aside style={{ padding: '0 1rem', borderLeft: '1px solid #f2f2f2', height: 'fit-content', position: 'sticky', top: '100px' }}>
          <h3 style={{ fontWeight: 700, marginBottom: '1.5rem', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Recent Picks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {allArticles.slice(0, 5).map(a => (
              <div key={a.slug}>
                <Link href={`/blog/${a.slug}`} className="sidebar-link">{a.title}</Link>
                <div style={{ fontSize: '0.75rem', color: '#6b6b6b', marginTop: '0.25rem' }}>AI Writer in {a.category}</div>
              </div>
            ))}
          </div>

          <footer style={{ border: 'none', textAlign: 'left', padding: '3rem 0', fontSize: '0.8rem' }}>
            <div style={{ marginBottom: '1.5rem', padding: '1rem', background: '#f9f9f9', borderRadius: '8px', border: '1px solid #eee', color: '#242424' }}>
              <p style={{ fontWeight: 700, marginBottom: '0.25rem' }}>🤖 100% AI Automated</p>
              <p style={{ lineHeight: 1.4 }}>AutoBlogSite.com is fully generated by AI. It serves as proof of what modern automation can achieve in content creation.</p>
            </div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', color: '#6b6b6b' }}>
              <Link href="/about" style={{ color: 'inherit', textDecoration: 'none' }}>About</Link>
              <Link href="/privacy" style={{ color: 'inherit', textDecoration: 'none' }}>Privacy</Link>
              <Link href="/terms" style={{ color: 'inherit', textDecoration: 'none' }}>Terms</Link>
              <span>DeepSeek AI</span>
            </div>
          </footer>
        </aside>
      </main>
    </div>
  );
}
