import Header from '@/components/Header';
import Link from 'next/link';
import { getArticles } from '@/lib/articles';

export default function Terms() {
  const allArticles = getArticles();

  return (
    <div>
      <Header />

      <main className="main-grid">
        <article className="reader-container" style={{ margin: '0', maxWidth: '100%' }}>
          <Link href="/" className="nav-link" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.5rem', fontSize: '0.9rem' }}>
            ← Home
          </Link>
          <h1 className="article-title">Terms of Service</h1>
          
          <div className="info-page-body">
            <p>By accessing <strong>AutoBlogSite.com</strong>, you agree to comply with these terms. This site is an AI automation experiment and provided "as is".</p>
            
            <h2>1. Acceptance of Terms</h2>
            <p>This site is for educational and experimental purposes. Every article you read is generated by Artificial Intelligence (AI Writer) without human intervention.</p>
            
            <h2>2. Content Usage</h2>
            <p>You may share and link to our content, but you must acknowledge AutoBlogSite.com as the source.</p>

            <h2>3. Limitation of Liability</h2>
            <p>AutoBlogSite.com and its creators shall not be liable for any errors or omissions in the content, nor for any losses or damages from the use of this information.</p>
          </div>
        </article>

        <aside style={{ padding: '0 1rem', borderLeft: '1px solid #f2f2f2', height: 'fit-content', position: 'sticky', top: '100px' }}>
          <h3 style={{ fontWeight: 700, marginBottom: '1.5rem', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Recent Picks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {allArticles.slice(0, 5).map(a => (
              <div key={a.slug}>
                <Link href={`/blog/${a.slug}`} className="sidebar-link">{a.title}</Link>
                <div style={{ fontSize: '0.75rem', color: '#6b6b6b', marginTop: '0.25rem' }}>AI Writer in {a.category}</div>
              </div>
            ))}
          </div>

          <div style={{ marginTop: '4rem', padding: '1.5rem', background: '#f9f9f9', borderRadius: '8px', border: '1px solid #eee' }}>
            <h4 style={{ marginBottom: '0.5rem', fontSize: '0.9rem' }}>🤖 AutoBlogSite.com</h4>
            <p style={{ fontSize: '0.8rem', color: '#6b6b6b', lineHeight: 1.5 }}>
              100% AI generated content. No human intervention.
            </p>
          </div>
        </aside>
      </main>

      <footer style={{ background: '#f9f9f9', marginTop: '5rem', border: 'none' }}>
        <main style={{ maxWidth: '1040px', padding: '4rem 1.5rem' }}>
           <p style={{ fontSize: '0.9rem', color: '#6b6b6b' }}>&copy; {new Date().getFullYear()} AutoBlogSite.com AI Experiment.</p>
        </main>
      </footer>
    </div>
  );
}
