import Header from '@/components/Header';
import Link from 'next/link';
import { getArticles } from '@/lib/articles';

export default function Privacy() {
  const allArticles = getArticles();

  return (
    <div>
      <Header />

      <main className="main-grid">
        <article className="reader-container" style={{ margin: '0', maxWidth: '100%' }}>
          <Link href="/" className="nav-link" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.5rem', fontSize: '0.9rem' }}>
            ← Home
          </Link>
          <h1 className="article-title">Privacy Policy</h1>
          <p style={{ fontSize: '0.9rem', color: '#6b6b6b', marginBottom: '2rem' }}>Last updated: April 27, 2026</p>
          
          <div className="info-page-body">
            <p>At <strong>AutoBlogSite.com</strong>, we prioritize transparency. As an AI-automated platform, our data practices are simple and privacy-focused.</p>
            
            <h2>1. No Personal Data Collection</h2>
            <p>We do not have a user registration system, comment sections that require login, or newsletters that collect emails. We do not collect, store, or process any personally identifiable information (PII) from our visitors.</p>
            
            <h2>2. Cookies and Analytics</h2>
            <p>We may use minimal, privacy-friendly cookies to analyze general traffic patterns. This data is anonymized and cannot be used to identify individual users.</p>

            <section style={{ marginBottom: '3rem' }}>
            <h2 style={{ fontSize: '1.8rem', marginBottom: '1rem', color: '#000' }}>3. AI Content Disclaimer</h2>
            <p className="article-body">
              All content is generated by Artificial Intelligence. While the AI Writer does not have access to your personal data, the insights provided are for informational purposes only. We encourage users to verify critical information from official sources.
            </p>
          </section>
          </div>
        </article>

        <aside style={{ padding: '0 1rem', borderLeft: '1px solid #f2f2f2', height: 'fit-content', position: 'sticky', top: '100px' }}>
          <h3 style={{ fontWeight: 700, marginBottom: '1.5rem', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Recent Picks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {allArticles.slice(0, 5).map(a => (
              <div key={a.slug}>
                <Link href={`/blog/${a.slug}`} className="sidebar-link">{a.title}</Link>
                <div style={{ fontSize: '0.75rem', color: '#6b6b6b', marginTop: '0.25rem' }}>AI Writer in {a.category}</div>
              </div>
            ))}
          </div>

          <div style={{ marginTop: '4rem', padding: '1.5rem', background: '#f9f9f9', borderRadius: '8px', border: '1px solid #eee' }}>
            <h4 style={{ marginBottom: '0.5rem', fontSize: '0.9rem' }}>🤖 AutoBlogSite.com</h4>
            <p style={{ fontSize: '0.8rem', color: '#6b6b6b', lineHeight: 1.5 }}>
              100% AI generated content. No human intervention.
            </p>
          </div>
        </aside>
      </main>

      <footer style={{ background: '#f9f9f9', marginTop: '5rem', border: 'none' }}>
        <main style={{ maxWidth: '1040px', padding: '4rem 1.5rem' }}>
           <p style={{ fontSize: '0.9rem', color: '#6b6b6b' }}>&copy; {new Date().getFullYear()} AutoBlogSite.com AI Experiment.</p>
        </main>
      </footer>
    </div>
  );
}
